name = "HypoSVI"
__version__ = "1.0"
__description__ = "HypoSVI: Earthquake location using Stein-variation gradient descent and deep neural network travel-time tables"
__license__ = "GPL v3.0"
__author__ = "Jonathan Smith, Kamyar Azizzadenesheli, Zachary E. Ross, Jack Muir"
__email__ = "jon_smith83@hotmail.co.uk"
